### ISSUE TITLE
No blisseydb datasource variable for dashboard 30.

### ISSUE THREAD

**Issue by kamieniarz** [UnownHash/Blissey#13]
https://github.com/UnownHash/Blissey/blob/master/default_files/grafana/30_dragonite_dimensioning_overview.json
There's `blissey` db hardcoded in 4 places - this dashbroad should have added second datasource for blisseydb database cause if someone has it named differently than `blissey` then boards won't work

**Comment by skelgaard** [comment]
the dragonite database is also hardcoded, should proberly be fixed in same instanse when fixing the blissey

**Comment by kamieniarz** [comment]
Oh right 👀 https://github.com/UnownHash/Blissey/blob/master/default_files/grafana/30_dragonite_dimensioning_overview.json#L588
I didn't catch that since my db is named same way 😅

**Comment by Fabio1988** [comment]
https://github.com/UnownHash/Blissey/pull/24
